// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

function Git(props) {
  var match = React.useState(function () {
        return "Anubhav-Ghosh1";
      });
  var setUsername = match[1];
  var username = match[0];
  var match$1 = React.useState(function () {
        return "";
      });
  var setLogin = match$1[1];
  var match$2 = React.useState(function () {
        return "";
      });
  var setName = match$2[1];
  var match$3 = React.useState(function () {
        
      });
  var setAvatarUrl = match$3[1];
  var avatarUrl = match$3[0];
  var match$4 = React.useState(function () {
        return "";
      });
  var setBio = match$4[1];
  var match$5 = React.useState(function () {
        return 0;
      });
  var setPublicRepos = match$5[1];
  var match$6 = React.useState(function () {
        return "";
      });
  var setLocation = match$6[1];
  var match$7 = React.useState(function () {
        return "";
      });
  var setTwitterUsername = match$7[1];
  var match$8 = React.useState(function () {
        return "";
      });
  var setBlog = match$8[1];
  var blog = match$8[0];
  var match$9 = React.useState(function () {
        return 0;
      });
  var setFollowing = match$9[1];
  var match$10 = React.useState(function () {
        return 0;
      });
  var setFollowers = match$10[1];
  var match$11 = React.useState(function () {
        return 0;
      });
  var setGists = match$11[1];
  React.useState(function () {
        return 0;
      });
  var handleOnChange = function (e) {
    var newValue = e.target.value;
    setUsername(function (param) {
          return newValue;
        });
  };
  var fetchData = async function () {
    var url = "https://api.github.com/users/" + username;
    var response = await globalThis.fetch(url);
    var data = await response.json();
    var blog = data.blog;
    var twitter_username = data.twitter_username;
    var $$location = data.location;
    var public_gists = data.public_gists;
    var public_repos = data.public_repos;
    var bio = data.bio;
    var following = data.following;
    var followers = data.followers;
    var avatar_url = data.avatar_url;
    var name = data.name;
    var login = data.login;
    setLogin(function (param) {
          return login;
        });
    setName(function (param) {
          return name;
        });
    setAvatarUrl(function (param) {
          return avatar_url;
        });
    setBio(function (param) {
          return bio;
        });
    setPublicRepos(function (param) {
          return public_repos;
        });
    setLocation(function (param) {
          return $$location;
        });
    setTwitterUsername(function (param) {
          return twitter_username;
        });
    setBlog(function (param) {
          return blog;
        });
    setFollowers(function (param) {
          return followers;
        });
    setFollowing(function (param) {
          return following;
        });
    setGists(function (param) {
          return public_gists;
        });
    console.log(data);
  };
  var handleOnClick = function (_event) {
    fetchData();
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("header", {
                      children: JsxRuntime.jsx("p", {
                            children: "Git Analysis",
                            className: "text-4xl font-semibold"
                          }),
                      className: "flex w-full mt-5 mb-5 justify-center"
                    }),
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsxs("form", {
                            children: [
                              JsxRuntime.jsx("input", {
                                    className: "w-full border-2 py-2 px-2 rounded-lg rounded-r-none",
                                    id: "",
                                    name: "",
                                    placeholder: "Enter Github User",
                                    type: "text",
                                    onChange: handleOnChange
                                  }),
                              JsxRuntime.jsx("button", {
                                    children: "Search",
                                    className: "bg-[#37bcc8] text-white px-2 rounded-lg rounded-l-none hover:bg-[#88ebf2] transition-all ease-in duration-200",
                                    onClick: handleOnClick
                                  })
                            ],
                            className: "md:w-[60%] w-[90%] flex justify-center",
                            onSubmit: (function (e) {
                                e.preventDefault();
                              })
                          }),
                      className: "bg-[#f1f5f8] pt-16 w-full flex justify-center"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("div", {
                                              children: JsxRuntime.jsx("svg", {
                                                    children: JsxRuntime.jsx("path", {
                                                          d: "M624 208h-64v-64c0-8.8-7.2-16-16-16h-32c-8.8 0-16 7.2-16 16v64h-64c-8.8 0-16 7.2-16 16v32c0 8.8 7.2 16 16 16h64v64c0 8.8 7.2 16 16 16h32c8.8 0 16-7.2 16-16v-64h64c8.8 0 16-7.2 16-16v-32c0-8.8-7.2-16-16-16zm-400 48c70.7 0 128-57.3 128-128S294.7 0 224 0 96 57.3 96 128s57.3 128 128 128zm89.6 32h-16.7c-22.2 10.2-46.9 16-72.9 16s-50.6-5.8-72.9-16h-16.7C60.2 288 0 348.2 0 422.4V464c0 26.5 21.5 48 48 48h352c26.5 0 48-21.5 48-48v-41.6c0-74.2-60.2-134.4-134.4-134.4z"
                                                        }),
                                                    className: "w-16 h-16 p-4 text-[#10e7ff]",
                                                    height: "200px",
                                                    width: "200px",
                                                    fill: "currentColor",
                                                    stroke: "currentColor",
                                                    strokeWidth: "0",
                                                    viewBox: "0 0 640 512",
                                                    xmlns: "http://www.w3.org/2000/svg"
                                                  }),
                                              className: "bg-[#e0fcff] flex justify-center items-center rounded-full"
                                            }),
                                        JsxRuntime.jsxs("div", {
                                              children: [
                                                JsxRuntime.jsx("p", {
                                                      children: match$9[0].toString(),
                                                      className: "text-xl font-semibold"
                                                    }),
                                                JsxRuntime.jsx("p", {
                                                      children: "Following"
                                                    })
                                              ],
                                              className: "flex flex-col text-left gap-2"
                                            })
                                      ],
                                      className: "flex lg:w-fit w-full bg-white py-2 px-5 hover:scale-105 rounded-lg shadow-lg hover:shadow-xl transition-all ease-in duration-200 items-center gap-5"
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("div", {
                                              children: JsxRuntime.jsxs("svg", {
                                                    children: [
                                                      JsxRuntime.jsx("path", {
                                                            d: "M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"
                                                          }),
                                                      JsxRuntime.jsx("circle", {
                                                            cx: "9",
                                                            cy: "7",
                                                            r: "4"
                                                          }),
                                                      JsxRuntime.jsx("path", {
                                                            d: "M23 21v-2a4 4 0 0 0-3-3.87"
                                                          }),
                                                      JsxRuntime.jsx("path", {
                                                            d: "M16 3.13a4 4 0 0 1 0 7.75"
                                                          })
                                                    ],
                                                    className: "w-16 h-16 p-4 text-purple-600",
                                                    height: "1em",
                                                    width: "1em",
                                                    fill: "none",
                                                    stroke: "currentColor",
                                                    strokeLinecap: "round",
                                                    strokeLinejoin: "round",
                                                    strokeWidth: "2",
                                                    viewBox: "0 0 24 24",
                                                    xmlns: "http://www.w3.org/2000/svg"
                                                  }),
                                              className: "bg-purple-200 flex justify-center items-center rounded-full"
                                            }),
                                        JsxRuntime.jsxs("div", {
                                              children: [
                                                JsxRuntime.jsx("p", {
                                                      children: match$10[0].toString(),
                                                      className: "text-xl font-semibold"
                                                    }),
                                                JsxRuntime.jsx("p", {
                                                      children: "Followers"
                                                    })
                                              ],
                                              className: "flex flex-col text-left gap-2"
                                            })
                                      ],
                                      className: "flex bg-white py-2 px-5 hover:scale-105 rounded-lg shadow-lg hover:shadow-xl transition-all ease-in duration-200 w-full items-center gap-5"
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("div", {
                                              children: JsxRuntime.jsx("svg", {
                                                    children: JsxRuntime.jsx("path", {
                                                          d: "M4 9H3V8h1v1zm0-3H3v1h1V6zm0-2H3v1h1V4zm0-2H3v1h1V2zm8-1v12c0 .55-.45 1-1 1H6v2l-1.5-1.5L3 16v-2H1c-.55 0-1-.45-1-1V1c0-.55.45-1 1-1h10c.55 0 1 .45 1 1zm-1 10H1v2h2v-1h3v1h5v-2zm0-10H2v9h9V1z",
                                                          fillRule: "evenodd"
                                                        }),
                                                    className: "w-16 h-16 p-4 text-[#ff44a5]",
                                                    height: "1em",
                                                    width: "1em",
                                                    fill: "currentColor",
                                                    stroke: "currentColor",
                                                    strokeWidth: "0",
                                                    viewBox: "0 0 12 16",
                                                    xmlns: "http://www.w3.org/2000/svg"
                                                  }),
                                              className: "bg-[#FFE0F0] flex justify-center items-center rounded-full"
                                            }),
                                        JsxRuntime.jsxs("div", {
                                              children: [
                                                JsxRuntime.jsx("p", {
                                                      children: match$5[0].toString(),
                                                      className: "text-xl font-semibold"
                                                    }),
                                                JsxRuntime.jsx("p", {
                                                      children: "Repos"
                                                    })
                                              ],
                                              className: "flex flex-col text-left gap-2"
                                            })
                                      ],
                                      className: "flex bg-white py-2 px-5 hover:scale-105 rounded-lg shadow-lg hover:shadow-xl transition-all ease-in duration-200 w-full items-center gap-5"
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("div", {
                                              children: JsxRuntime.jsx("svg", {
                                                    children: JsxRuntime.jsx("path", {
                                                          d: "M7.5 5L10 7.5 7.5 10l-.75-.75L8.5 7.5 6.75 5.75 7.5 5zm-3 0L2 7.5 4.5 10l.75-.75L3.5 7.5l1.75-1.75L4.5 5zM0 13V2c0-.55.45-1 1-1h10c.55 0 1 .45 1 1v11c0 .55-.45 1-1 1H1c-.55 0-1-.45-1-1zm1 0h10V2H1v11z",
                                                          fillRule: "evenodd"
                                                        }),
                                                    className: "w-16 h-16 p-4 text-[#ffd931]",
                                                    height: "1em",
                                                    width: "1em",
                                                    fill: "currentColor",
                                                    stroke: "currentColor",
                                                    strokeWidth: "0",
                                                    viewBox: "0 0 12 16",
                                                    xmlns: "http://www.w3.org/2000/svg"
                                                  }),
                                              className: "bg-[#FFFBEA] flex justify-center items-center rounded-full"
                                            }),
                                        JsxRuntime.jsxs("div", {
                                              children: [
                                                JsxRuntime.jsx("p", {
                                                      children: match$11[0].toString(),
                                                      className: "text-xl font-semibold"
                                                    }),
                                                JsxRuntime.jsx("p", {
                                                      children: "Gits"
                                                    })
                                              ],
                                              className: "flex flex-col text-left gap-2"
                                            })
                                      ],
                                      className: "flex bg-white py-2 px-5 hover:scale-105 rounded-lg shadow-lg hover:shadow-xl transition-all ease-in duration-200 w-full items-center gap-5"
                                    })
                              ],
                              className: "flex flex-col md:flex-row gap-5"
                            }),
                        JsxRuntime.jsx("div", {
                              children: avatarUrl !== undefined ? JsxRuntime.jsx("div", {
                                      children: JsxRuntime.jsx("div", {
                                            children: JsxRuntime.jsx("div", {
                                                  children: JsxRuntime.jsxs("div", {
                                                        children: [
                                                          JsxRuntime.jsx("img", {
                                                                className: "md:w-40 w-16 rounded-full",
                                                                alt: "Avatar",
                                                                height: "50",
                                                                src: avatarUrl
                                                              }),
                                                          JsxRuntime.jsxs("div", {
                                                                children: [
                                                                  JsxRuntime.jsx("p", {
                                                                        children: "@" + match$1[0]
                                                                      }),
                                                                  JsxRuntime.jsx("p", {
                                                                        children: match$2[0]
                                                                      }),
                                                                  JsxRuntime.jsx("p", {
                                                                        children: match$4[0],
                                                                        className: "text-wrap"
                                                                      }),
                                                                  JsxRuntime.jsxs("div", {
                                                                        children: [
                                                                          JsxRuntime.jsx("p", {
                                                                                children: "@ " + match$7[0]
                                                                              }),
                                                                          JsxRuntime.jsxs("div", {
                                                                                children: [
                                                                                  JsxRuntime.jsx("img", {
                                                                                        className: "w-4 h-4",
                                                                                        alt: "",
                                                                                        src: "https://cdn-icons-png.flaticon.com/512/3214/3214746.png"
                                                                                      }),
                                                                                  JsxRuntime.jsx("a", {
                                                                                        children: blog,
                                                                                        href: blog
                                                                                      })
                                                                                ],
                                                                                className: "flex items-center gap-2"
                                                                              })
                                                                        ],
                                                                        className: "flex lg:flew-row flex-col items-center gap-2"
                                                                      })
                                                                ],
                                                                className: "text-center"
                                                              })
                                                        ],
                                                        className: "flex flex-col lg:flex-row items-center gap-5"
                                                      }),
                                                  className: "flex flex-col items-center gap-10"
                                                }),
                                            className: "flex lg:flex-col flex-row gap-10 items-center justify-center"
                                          }),
                                      className: "flex lg:flex-row flex-col"
                                    }) : JsxRuntime.jsx("p", {
                                      children: "Search for user"
                                    }),
                              className: "flex rounded-lg flex-col items-center justify-center bg-white h-fit py-10 lg:w-[60%] w-full border-2"
                            })
                      ],
                      className: "bg-[#f1f5f8] lg:pt-0 pt-24 h-screen flex flex-col items-center gap-10 justify-center"
                    })
              ]
            });
}

var make = Git;

export {
  make ,
}
/* react Not a pure module */
