// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Git from "./components/Git.res.mjs";
import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  React.useState(function () {
        return 0;
      });
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx(Git.make, {})
            });
}

var make = App;

export {
  make ,
}
/* Git Not a pure module */
